name: Check Build

on:
  pull_request:
    types: [opened, edited]
  push:
    # only trigger on branches, not on tags
    branches: "**"

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      run: npm run build
