name: "Check Mergeability"

on:
  pull_request:
    # With "edited" it runs on PR title updates
    types: [opened, edited, synchronize, reopened]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
      - run: npm install
      - run: npm run build --if-present
# jobs:
#   check-main:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: bennycode/stop-merging@v0.1.3
#         with:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GIT_BRANCH: "main"
#           BYPASS_PREFIX: "fix"
